server:
  port: 8080

spring:
  data:
    redis:
      host: 192.168.99.100
      port: 6379
  cloud:
    gateway:
      routes:
        - id: integerModule
          uri: http://localhost:8081/
          predicates:
            - Path=/integer/**
          filters:
            - name: RequestRateLimiter
              args:
                # 1 request/sec
#                redis-rate-limiter.replenishRate: 10
#                redis-rate-limiter.burstCapacity: 20
#                redis-rate-limiter.requestedTokens: 1
                # 1 request/min
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 60
#                redis-rate-limiter.requestedTokens: 60
                # test
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
                redis-rate-limiter.requestedTokens: 1
                denyEmptyKey: false
        - id: doubleModule
          uri: http://localhost:8082/
          predicates:
            - Path=/double/**

logging:
  level:
    org.springframework: DEBUG